spring.application.name=reporte
server.port=8091
spring.datasource.url=jdbc:mysql://localhost:3307/reporte_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

microservices.ventas.url=http://localhost:8088/api/v1/venta
microservices.inventario.url=http://localhost:8084/api/v1/inventarios
microservices.sucursales.url=http://localhost:8083/api/v1/sucursales
