spring.application.name=venta
server.port=8088
spring.datasource.url=jdbc:mysql://localhost:3307/venta_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

microservices.inventario.descontar-stock-url=http://localhost:8084/api/v1/inventarios/ventas/descontar
microservices.perfume.obtener-url=http://localhost:8084/api/v1/perfumes/{id}
microservices.producto.obtener-url=http://localhost:8084/api/v1/productos/{id}
microservices.producto.disponibilidad-url=http://localhost:8084/api/v1/productos/{id}/disponibilidad
microservices.sucursal.obtener-url=http://localhost:8083/api/v1/sucursales/{id}
