spring:
  application:
    name: gateway-perfulandia

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: usuario
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/usuarios,/api/v1/usuarios/**,/api/v1/auth,/api/v1/auth/**,/api/v1/roles,/api/v1/roles/**,/api/v1/permisos,/api/v1/permisos/**

            - id: cliente
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/clientes,/api/v1/clientes/**

            - id: sucursales
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/sucursales,/api/v1/sucursales/**

            - id: inventario
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/perfumes,/api/v1/perfumes/**,/api/v1/productos,/api/v1/productos/**,/api/v1/inventarios,/api/v1/inventarios/**,/api/v1/categorias-producto,/api/v1/categorias-producto/**,/api/v1/movimientos-inventario,/api/v1/movimientos-inventario/**,/api/v1/alertas-stock,/api/v1/alertas-stock/**,/api/v1/resenas-producto,/api/v1/resenas-producto/**,/api/v1/usuarios-inventario,/api/v1/usuarios-inventario/**

            - id: abastecimiento
              uri: http://localhost:8085
              predicates:
                - Path=/api/proveedores,/api/proveedores/**,/api/ordenes-compra,/api/ordenes-compra/**,/api/recepciones,/api/recepciones/**

            - id: pedido
              uri: http://localhost:8086
              predicates:
                - Path=/api/pedidos,/api/pedidos/**,/api/carritos,/api/carritos/**,/api/cupones,/api/cupones/**

            - id: pago
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/pagos,/api/v1/pagos/**

            - id: ventas
              uri: http://localhost:8088
              predicates:
                - Path=/api/v1/venta,/api/v1/venta/**

            - id: despacho
              uri: http://localhost:8089
              predicates:
                - Path=/api/despachos,/api/despachos/**

            - id: soporte
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/soporte,/api/v1/soporte/**

            - id: reporte
              uri: http://localhost:8091
              predicates:
                - Path=/api/v1/reportes,/api/v1/reportes/**

            - id: monitoreo
              uri: http://localhost:8092
              predicates:
                - Path=/api/monitoreo,/api/monitoreo/**,/api/registros,/api/registros/**,/api/alertas,/api/alertas/**,/api/respaldos,/api/respaldos/**

server:
  port: 8080
