spring.application.name=monitoreo
server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3307/monitoreo_bd?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

monitoreo.servicios=usuario=http://localhost:8081/api/v1/usuarios,cliente=http://localhost:8082/api/v1/clientes,sucursales=http://localhost:8083/api/v1/sucursales,inventario=http://localhost:8084/api/v1/productos,abastecimiento=http://localhost:8085/api/proveedores,pedido=http://localhost:8086/api/pedidos,pago=http://localhost:8087/api/v1/pagos,ventas=http://localhost:8088/api/v1/venta,despacho=http://localhost:8089/api/despachos,soporte=http://localhost:8090/api/v1/soporte/tickets,reporte=http://localhost:8091/api/v1/reportes
